### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/flatzingo#6]
Parameters in flatzinc describe constants and can occur in places where also variables can occur.
We either have to change the encoding to support this or simply replace all parameters with their respective values in the parser.
In the queens example we have a parameter array:
```
parameter(array(2,int),"X_INTRODUCED_4_").    
in_array("X_INTRODUCED_4_",0,"1").
in_array("X_INTRODUCED_4_",1,"-1").
```
These two lines set the values for the parameters in the array.
I could not yet figure out how a single parameter is set to its value.

**Comment by MaxOstrowski** [comment]
Parameters have fixed values and must be assigned values:

`<par-decl-item> ::= <par-type> ":" <var-par-identifier> "=" <par-expr> ";"`

where <par-type> is a parameter type, <var-par-identifier> is an identifier, and <par-expr> is a literal value (either a basic integer, float or bool literal, or a set or array of such literals).

Annotations are not permitted anywhere in parameter declarations.

Examples:

```
float: pi = 3.141;
array [1..7] of int: fib = [1, 1, 2, 3, 5, 8, 13];
bool: beer_is_good = true;
```

**Comment by sthiele** [comment]
> I could not yet figure out how a single parameter is set to its value.

Aus `int: x = 2;` wird `parameter(int, "x","2").`
Eigentlich sollte es `parameter(int, "x",2).` sein.

**Comment by MaxOstrowski** [comment]
Vielleicht ne command line option ob Zahlen als Strings oder nicht ausgegeben werden.
